# Github workflow runner for Docker Multi-Arch using QEMU, Buildx for amd64 & arm64
name: Docker Multi-Arch

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build for amd64/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
        # Setup hardware emulator using QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
        # Setup Docker Buildx for multi-arch images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log into registry ${{ env.REGISTRY }}
        #if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
